# Generated by Django 5.2.7 on 2025-11-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='movimiento',
            table='movimientos',
        ),
    ]
