# Generated by Django 5.2.7 on 2025-10-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
